[theme]
base = "dark"
primaryColor = "#4ecdc4"
backgroundColor = "#101319"
secondaryBackgroundColor = "#344055"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
address = 0.0.0.0
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[logger]
level = "error"
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "auto"
port = 8501

[browser]
gatherUsageStats = false
